version: v2

global:
  runner:
    os_image: ubuntu
  variables:
    - RACK_ENV=test

tasks:
  build-docker-image:
    steps:
      - checkout
      - docker/build:
          image: sravanibikkina/nodek8s
          dockerfile: Dockerfile
          context: .
 
  deploy-to-kubernetes-cluster:
    steps:
      - checkout
      - commands:
          #Deploy to minikube cluster
        - kubectl apply -f pods.yaml
        - kubectl apply -f services.yaml

