global:
  runner:
    os_image: ubuntu

tasks:
  build-docker-image:
    steps:
      - checkout
      - docker/build:
          image: sravanibikkina/pythoncicd
          dockerfile: Dockerfile
          context: .
 
  deploy-to-kubernetes cluster:
    steps:
      - checkout
      - commands:
          #Deploy to minikube cluster
        - kubectl apply -f deployment.yaml
        - kubectl apply -f services.yaml

