apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeak8s
      image: sravanibikkina/nodek8s:latest
      ports:
	    - containerPort: 8081
